### ISSUE TITLE
Compile external modules

### ISSUE THREAD

**Issue by nigredo13** [beeware/Python-Android-support#30]
Hi all,
first of all, many thanks for your project, I tried it and works fine !
I 'd ask you, how can I compile some external modules ?
I'll need cryptography, which depends on cffi, all of them contains compiled modules.
Is there a way ?
Thaks.
marco

**Comment by freakboy3742** [comment]
As noted on beeware/briefcase#471, this is a known issue; it's resolvable, but there's no "simple" solution. The core of the fix is outside the remit of this specific project (Python-Android-spport) - it requires support in the Python packaging ecosystem for the specific requirements of mobile packaging.
